version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/encoders/audio"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "jina"
        dependency-type: "direct"
    open-pull-requests-limit: 10
    
 - package-ecosystem: "docker"
    directory: "/encoders/audio"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "jina"
        dependency-type: "direct"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/encoders/image"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "jina"
        dependency-type: "direct"
    open-pull-requests-limit: 100
    
  - package-ecosystem: "pip"
    directory: "/encoders/multimodal"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "jina"
        dependency-type: "direct"
    open-pull-requests-limit: 100

  - package-ecosystem: "pip"
    directory: "/encoders/nlp"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "jina"
        dependency-type: "direct"
    open-pull-requests-limit: 100

  - package-ecosystem: "pip"
    directory: "/encoders/numeric"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "jina"
        dependency-type: "direct"
    open-pull-requests-limit: 100

  - package-ecosystem: "pip"
    directory: "/encoders/video"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "jina"
        dependency-type: "direct"
    open-pull-requests-limit: 100
