version: 2
updates:   
  - package-ecosystem: "docker"
    directory: "/encoders/audio/ChromaPitchEncoder"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    
  - package-ecosystem: "docker"
    directory: "/encoders/audio/MFCCTimbreEncoder"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    
  - package-ecosystem: "docker"
    directory: "evaluators/rank/NdcgEvaluator"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
