version: 2
updates:
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/image/FiveImageCropper
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/image/RandomImageCropper
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/image/SlidingWindowImageCropper
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/image/TorchObjectDetectionSegmenter
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/audio/SlidingWindowAudioSlicer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/audio/AudioSlicer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/nlp/PDFExtractorSegmenter
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/nlp/NLTKSentencizer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/nlp/JiebaSegmenter
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/nlp/JiebaSegmenter/tests
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/nlp/DeepSegmenter
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: segmenters/nlp/SpacySentencizer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: classifiers/nlp/ZeroShotTFClassifier
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/FeatureAgglomerationEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/UMAPEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/FastICAEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/RandomSparseEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/TSNEEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/CompressionVaeEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/IncrementalPCAEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/numeric/RandomGaussianEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/multimodal/TirgMultimodalEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/CustomImageTorchEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/ImageKerasEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/BigTransferEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/ImageOnnxEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/ImageTorchEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/ImagePaddlehubEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/CustomKerasImageEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/VSEImageEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/image/TirgImageEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/video/VideoTorchEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/video/VideoPaddleEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/audio/ChromaPitchEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/audio/MFCCTimbreEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/audio/Wav2VecSpeechEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/TransformerTFEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/FlairTextEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/UniversalSentenceEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/TransformerTorchEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/LaserEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/FarmTextEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/VSETextEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: encoders/nlp/TextPaddlehubEncoder
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/image/ImageReader
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/image/ImageCropper
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/image/AlbumentationsCrafter
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/image/ImageResizer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/image/ImageFlipper
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/image/ImageNormalizer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/image/CenterImageCropper
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/audio/AudioMonophoner
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/audio/AudioNormalizer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/audio/AudioReader
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: crafters/nlp/TikaExtractor
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: evaluators/text/EditDistanceEvaluator
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: evaluators/text/BleuEvaluator
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: evaluators/text/GleuEvaluator
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: evaluators/text/RougeEvaluator
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/MilvusIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/FaissIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/SptagIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/AnnoyIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/NGTIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/NmsLibIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/ScannIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/vector/ZarrIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/keyvalue/RedisDBIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/keyvalue/LevelDBIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: indexers/keyvalue/MongoDBIndexer
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: rankers/LightGBMRanker
- package-ecosystem: pip
  schedule:
    interval: daily
  allow:
  - dependency-name: jina
    dependency-type: direct
  directory: rankers/LevenshteinRanker
