version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
    - dependency-name: "jina"
      dependency-type: "direct"
    open-pull-requests-limit: 100
